### ISSUE TITLE
What's the point of OptionalSObject?

### ISSUE THREAD

**Issue by Firtzberg** [ipavlic/apex-fp#15]
I see you use the `OptionaSObject` when in the [find()](https://github.com/ipavlic/apex-fp/blob/94b2d363d49a253b7800a4c426d66c7cbc13e7b7/sfdx-source/apex-fp/main/classes/collection/SObjectCollection.cls#L430) method.

I thought you can assign the value null to an sObject, as in `sObject x = null`, so there's no need for `OptionaSObject`.

**Comment by ipavlic** [comment]
Hi, the idea behind `Optional`* is declarative handling of values that do not exist (are not found). It's a common pattern in languages that do not differentiate between three possible outcomes: "does not exist", "exists, but is not defined", "exists and it's defined". For example, Javascript might have `undefined` and `null`. Haskell might have `maybe` which is either just value or nothing.

One can `find()` and then choose a default value with `orElse` or throw an exception if nothing is found with `orElseThrow` or check for presence and return the value with `isPresent` and `get`. In any case, the hope is that `null` values are better handled, and that you don't have to write repetitive code to do it.
